project:
  type: website

website:
  title: "Methods"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Workshops"
        menu:
          - text: "Einführung in R & RStudio"
            href: workshops/ws1/index.qmd
          - text: "Datenvisualisierung mit ggplot2"
            href: workshops/ws2/index.qmd
          #- text: "Reproduzierbare Berichte mit Quarto"
          #  href: workshops/ws3/index.qmd

  sidebar:
    - id: workshop1
      title: ""
      style: docked
      background: white
      contents:
        - text: "Zum Workshop – Tag 1"
          href: workshops/ws1/day1.qmd
        - text: "Zum Workshop – Tag 2"
          href: workshops/ws1/day2.qmd

    - id: workshop2
      title: ""
      style: docked
      background: white
      contents:
        - text: "Zum Workshop – Tag 1"
          href: workshops/ws2/day1.qmd
        - text: "Zum Workshop – Tag 2"
          href: workshops/ws2/day2.qmd

  page-footer:
    left: "© 2026 Arieja Farugie"
    right: "Made with [Quarto](https://quarto.org)"

format:
  html:
    theme: default
    css: styles.css
    mainfont: "Mulish"
    monofont: "JetBrains Mono, monospace"
    fontsize: 1rem
    linestretch: 1.7
    toc: true
    toc-depth: 2
    smooth-scroll: true
    code-copy: true
    code-overflow: scroll
